### ISSUE TITLE
Serializer still depends on GDAL?

### ISSUE THREAD

**Issue by flesser** [makinacorpus/django-geojson#75] opened 2016-02-23 21:05 UTC
I encountered a strange issue. On my development machine, everything worked fine. When I tried to run my project on another computer, I suddenly got errors like the following when saving a PointField:

``` python
>>> self.pointField = {'type': 'Point', 'coordinates': [lon, lat]}
>>> self.save()
[2016-28-23 20:28:53] ERROR [django.contrib.gis:45] Error creating geometry from value '{
  "type":"Point",
  "coordinates":[
    7.09,
    50.72
  ]
}' (Initializing geometry from JSON input requires GDAL.)
```

After performing a `sudo apt-get install gdal-bin` (which also installed a whole bunch of other geospatial libraries), the errors were gone. But the whole point of using django-geojson is that I don't need to install geospatial libraries just to store some Points and have nice Leaflet widgets.

On both computers, Django runs in the same freshly installed Python3-virtualenv:

``` bash
$ pip freeze
Django==1.9.2
PyYAML==3.11
crispy-forms-foundation==0.5.3
django-crispy-forms==1.6.0
django-geojson==2.9.0
django-leaflet==0.18.0
jsonfield==1.0.3
mysqlclient==1.3.7
pytz==2015.7
six==1.10.0
xlwt==1.0.0
```

**Comment by leplatrem** [comment] 2016-03-02 12:42
That's a string from `contrib.gis` indeed!

Can you check the type of your `PointField` ? It should be `djgeojson.fields.PointField`.

**Comment by fx3O2** [comment] 2016-03-03 20:44
I can confirm this, had the same issue on arch after installing `gdal` all works fine!

**Comment by dzh21** [comment] 2016-06-02 22:22
the same problem, after `sudo aptitude install gdal-bin` all good

**Comment by maltem-za** [comment] 2016-07-19 12:44
Confirmed - with the same solution as mentioned above.

Not really surprising considering the following import pattern is used throughout django-geojson & django-leaflet:

```python
# from django-geojson serializers.py
try:
    from django.contrib.gis.geos import WKBWriter
    from django.contrib.gis.geos import GEOSGeometry
    from django.contrib.gis.db.models.fields import GeometryField
except (ImportError, ImproperlyConfigured):
    from .nogeos import WKBWriter
    from .nogeos import GEOSGeometry
    from .fields import GeometryField
```

As `contrib.gis` comes with Django I don't see how this was intended to prefer the `nogeos` stuff. Perhaps `contrib.gis` used to raise `ImproperlyConfigured` when gdal isn't present? However django-leaflet only handles `ImportError` in all the places I looked...

**Comment by cgestes** [comment] 2017-12-06 01:47
Encountered the same since I updated to 2.11.0 :(

(the bug is not present in 2.10.0)

**Comment by leplatrem** [comment] 2017-12-06 13:32
You can check the diff
https://github.com/makinacorpus/django-geojson/compare/2.10.0...2.11.0

@Gagaro could you update the Github releases page please. And also, use PRs where Travis tests remain green instead of committing to master (easier to follow regressions etc.). Thanks!

**Comment by Gagaro** [comment] 2017-12-06 14:14
Travis tests are green, the only PR I merged without travis was the pip install one which was very simple (but still needed travis...).

And yes I should update the releases.

**Comment by coredumperror** [comment] 2018-10-23 21:56
Is there any chance that this issue could be resolved? I just started using django-geojson, and I'm getting the same error as @flesser for apparently the same reason. I don't want to install gdal just to make an import I don't plan to use not crash. I cannot downgrade to 2.10 because my project uses Django 2.x.

**Closed** 2018-12-05 13:49 UTC
